#/particle reddust ~ ~1 ~ 1 1 1 0 200
on swap hand items:
    if name of player's tool is "&4&l도쿄구울 도구":
        cancel event
        set {_loc} to location 1.5 meters above player
        set {_x} to x-coordinate of {_loc}
        set {_y} to y-coordinate of {_loc}
        set {_z} to z-coordinate of {_loc}

        execute console command "/particle dust 1 0 0 2 %{_x}% %{_y}% %{_z}% 1 1 1 0 100"
#/particle cloud ~ ~ ~ 0 2 0 0.00001 500 (연쇄)
#/particle cloud ~ ~ ~ 2 0.5 2 0.00001 500
on jump:
    if player is sneaking:
        if name of player's tool is "&4&l도쿄구울 도구":
            set {_loc} to location of player
            set {_x} to x-coordinate of {_loc}
            set {_y} to y-coordinate of {_loc}
            set {_z} to z-coordinate of {_loc}

            execute console command "/particle cloud %{_x}% %{_y}% %{_z}% 0 2 0 0.00001 500"
            execute console command "/particle cloud %{_x}% %{_y}% %{_z}% 2 0.5 2 0.00001 500"
#/particle crit ~ ~1.5 ~ 1 0 0 0.001 150
#/particle crit ~ ~1.5 ~ 0 0.5 0.5 0.0000001 150 (연쇄)
on rightclick:
    if name of player's tool is "&4&l도쿄구울 도구":

        delete {_whyhoe::*}
        add dirt to {_whyhoe::*}
        add grass block to {_whyhoe::*}
        add coarse dirt to {_whyhoe::*}
        add farmland to {_whyhoe::*}
        add dirt path to {_whyhoe::*}
        add rooted dirt to {_whyhoe::*}

        if {_whyhoe::*} contains event-block:
            cancel event

        if player is sneaking:
            set {_loc} to location 1.5 meters above player
            set {_x} to x-coordinate of {_loc}
            set {_y} to y-coordinate of {_loc}
            set {_z} to z-coordinate of {_loc}

            execute console command "/particle crit %{_x}% %{_y}% %{_z}% 1 0 0 0.001 150"
            execute console command "/particle crit %{_x}% %{_y}% %{_z}% 0 0.5 0.5 0.0000001 150"
        else:
            set {_loc} to location 1.5 meters in front of player
            add 1 to y-coordinate of {_loc}

            set {_x} to x-coordinate of {_loc}
            set {_y} to y-coordinate of {_loc}
            set {_z} to z-coordinate of {_loc}

            execute console command "/particle crit %{_x}% %{_y}% %{_z}% 0 0 1.5 0.00001 150"
#/particle reddust ~ ~1.5 ~ 1 0 0 0 150
#/particle reddust ~ ~1.5 ~ 0 0.5 0.5 0 150 (연쇄)
on leftclick:
    if player is sneaking:
        if name of player's tool is "&4&l도쿄구울 도구":
            set {_loc} to location 1.5 meters above player

            set {_x} to x-coordinate of {_loc}
            set {_y} to y-coordinate of {_loc}
            set {_z} to z-coordinate of {_loc}

            execute console command "/particle dust 1 0 0 1 %{_x}% %{_y}% %{_z}% 1 0 0 0 150"
            execute console command "/particle dust 1 0 0 1 %{_x}% %{_y}% %{_z}% 0 0.5 0.5 0 150"

on break:
    if name of player's tool is "&4&l도쿄구울 도구":
        cancel event
