#/particle reddust ~ ~1 ~ 1 1 1 0 200
on swap hand items:
    if name of player's tool is "&4&l도쿄구울 도구":
        cancel event
        set {_loc} to location 1.5 meters above player
        draw 100 of dust using dustOption(red, 2) at {_loc} with offset vector(1, 1, 1) with extra 0
#/particle cloud ~ ~ ~ 0 2 0 0.00001 500 (연쇄)
#/particle cloud ~ ~ ~ 2 0.5 2 0.00001 500
on jump:
    if player is sneaking:
        if name of player's tool is "&4&l도쿄구울 도구":
            set {_loc} to location of player
            make 500 of cloud at {_loc} with offset vector(0, 2, 0) with extra 0.00001
            make 500 of cloud at {_loc} with offset vector(2, 0.5, 2) with extra 0.00001
#/particle crit ~ ~1.5 ~ 1 0 0 0.001 150
#/particle crit ~ ~1.5 ~ 0 0.5 0.5 0.0000001 150 (연쇄)
on rightclick:
    if name of player's tool is "&4&l도쿄구울 도구":
        delete {_whyhoe::*}
        add dirt to {_whyhoe::*}
        add grass block to {_whyhoe::*}
        add coarse dirt to {_whyhoe::*}
        add farmland to {_whyhoe::*}
        add dirt path to {_whyhoe::*}
        add rooted dirt to {_whyhoe::*}
        
        if {_whyhoe::*} contains event-block:
            cancel event
        
        if player is sneaking:
            set {_loc} to location 1.5 meters above player
            make 150 of crit at {_loc} with offset vector(1, 0, 0) with extra 0.001
            make 150 of crit at {_loc} with offset vector(0, 0.5, 0.5) with extra 0.0000001
        else:
            # 커맨드 ~ ~3 ~와 동일하게 발 위치에서 정확히 3미터 위로 설정
            set {_loc} to location 1.5 meter in front of player
            add 1 to y-coord of {_loc}
            # 0 0 1.5 오프셋을 그대로 적용하여 Z축으로 길게 형성
            make 150 of crit at {_loc} with offset vector(0, 0, 1.5) with extra 0.00001
#/particle reddust ~ ~1.5 ~ 1 0 0 0 150
#/particle reddust ~ ~1.5 ~ 0 0.5 0.5 0 150 (연쇄)
on leftclick:
    if player is sneaking:
        if name of player's tool is "&4&l도쿄구울 도구":
            set {_loc} to location 1.5 meters above player
            draw 150 of dust using dustOption(red, 1) at {_loc} with offset vector(1, 0, 0) with extra 0
            draw 150 of dust using dustOption(red, 1) at {_loc} with offset vector(0, 0.5, 0.5) with extra 0

on break:
    if name of player's tool is "&4&l도쿄구울 도구":
        cancel event
